name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [11-jdk, 17-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew build --stacktrace